# Generated by Django 6.0.3 on 2026-04-10 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('workspace_id', models.AutoField(primary_key=True, serialize=False)),
                ('workspace_name', models.CharField(blank=True, max_length=150, null=True)),
                ('tokens', models.IntegerField(default=0)),
                ('collection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to='workspace.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('retrieval_type', models.CharField(max_length=50)),
                ('re_ranker', models.CharField(max_length=50)),
                ('embedding_model', models.CharField(max_length=100)),
                ('chunking_strategy', models.CharField(max_length=50)),
                ('distance_metric', models.CharField(max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=1.0)),
                ('top_k', models.IntegerField(default=5)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'user')},
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='users',
            field=models.ManyToManyField(related_name='workspaces', through='workspace.WorkspaceMembership', to='workspace.user'),
        ),
    ]
