# Generated by Django 5.2.7 on 2026-02-08 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('workspace_id', models.AutoField(primary_key=True, serialize=False)),
                ('tokens', models.IntegerField(default=0)),
                ('collection_id', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('retrieval_type', models.CharField(max_length=50)),
                ('re_ranker', models.CharField(max_length=50)),
                ('embedding_model', models.CharField(max_length=100)),
                ('chunking_strategy', models.CharField(max_length=50)),
                ('distance_metric', models.CharField(max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('top_p', models.FloatField(default=1.0)),
                ('top_k', models.IntegerField(default=5)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='workspace.workspace')),
            ],
        ),
    ]
